name: Cache ~/.npm
on: workflow_call
jobs:
  cache:
    steps:
      - uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
      - run: npm install
      - run: npx lerna bootstrap