name: Publish
on:
  release:
    types: [created]
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - run: npm run test
      
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - run: npm run build

  publish-npm:
    needs: [test, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
      - run: npm install && npx lerna bootstrap
      - run: npm run build
      - run: npx lerna exec -- npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  publish-gpr:
    needs: [test, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
      - run: npm install && npx lerna bootstrap
      - run: npm run build
      - run: npx lerna exec -- npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

  # publish-gpr:
  #   needs: [test, build]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: ./.github/actions/setup
  #     - uses: actions/download-artifact@v2
#         with:
#           name: build
#       - run: echo "registry=https://npm.pkg.github.com/" > ./**/.npmrc
#       - run: echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" >> ./**/.npmrc
#         env:
#           NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
#       - run: npx lerna publish --yes
#         env:
#           NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
