name: Publish
on:
  push:
    branches: main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - run: npm run test
      
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - run: npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: |
            .
            !.git
            !**/node_modules

  publish-npm:
    needs: [test, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - uses: actions/download-artifact@v2
        with:
          name: build
      - run: ls packages/*/

  publish-gpr:
    needs: [test, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - uses: actions/download-artifact@v2
        with:
          name: build
      - run: ls packages/*/

  # publish-gpr:
  #   needs: [create-release]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/download-artifact@v2
  #       with:
  #         name: build
  #     - run: ls packages/*/
    # - uses: plutotcool/release@v1
    #   with:
    #     github_token:  ${{secrets.GITHUB_TOKEN}}
    #     npm_token: ${{secrets.npm_token}}
    # - run: ls packages/*/
    # - uses: plutotcool/release@v1
    #   with:
    #     github_token:  ${{secrets.GITHUB_TOKEN}}
    #     npm_token: ${{secrets.npm_token}}
  