name: Publish
on:
  release:
    types: [released]
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - run: npm run test
      
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - run: npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: |
            .
            !.git
            !**/node_modules

  publish-npm:
    needs: [test, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - uses: actions/download-artifact@v2
        with:
          name: build
      - run: echo "registry=https://registry.npmjs.org/" > ./**/.npmrc
      - run: echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" >> ./**/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      - run: npx lerna publish --yes
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  publish-gpr:
    needs: [test, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - uses: actions/download-artifact@v2
        with:
          name: build
      - run: echo "registry=https://npm.pkg.github.com/" > ./**/.npmrc
      - run: echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" >> ./**/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: npx lerna publish --yes
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
