name: Release
on:
  push:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: ./.github/workflows/reusable/npm-cache.yml@latest
      - uses: ./.github/workflows/test.yml@latest
  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14
    - uses: ./.github/workflows/reusable/npm-cache.yml@latest
    - uses: ./.github/workflows/build.yml@latest
    - run: ls packages/*/
    # - uses: plutotcool/release@v1
    #   with:
    #     github_token:  ${{secrets.GITHUB_TOKEN}}
    #     npm_token: ${{secrets.npm_token}}