name: Run Tests
on:
  push:
    branches:
      - '**'
      - '!main'
    tags:
      - '!v*'
  pull_request:
    branches:
      - '**'
    tags:
      - '!v*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - run: npm run test
      - uses: codecov/codecov-action@v2