name: Run Tests
on:
  pull_request:
    branches: dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - run: npm run test
      - uses: codecov/codecov-action@v2